name: OCI ARM Instance Creator
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  create-instance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install --no-dev
      - name: Create private key file
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
      - name: Run instance creator
        run: php index.php
